apiVersion: v2
name: rancher-webhook
description: ValidatingAdmissionWebhook for Rancher types
version: "999"
appVersion: "999"
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/release-name: rancher-webhook
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/rancher-version: ">= 2.9.0-0 < 2.10.0-0"
  catalog.cattle.io/kube-version: "< 1.31.0-0"
